CREATE DATABASE IF NOT EXISTS liveledger
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE liveledger;

CREATE TABLE IF NOT EXISTS users (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(190) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS shows (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  show_date DATE NOT NULL,
  venue VARCHAR(150) NOT NULL,
  city VARCHAR(120) NOT NULL,
  artist VARCHAR(150) NOT NULL,
  user_id INT UNSIGNED NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_shows_user
    FOREIGN KEY (user_id) REFERENCES users(id)
    ON DELETE CASCADE,
  INDEX idx_shows_order (show_date DESC, artist ASC)
);
