CREATE DATABASE IF NOT EXISTS liveledger
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE liveledger;

CREATE TABLE IF NOT EXISTS shows (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  show_date DATE NOT NULL,
  venue VARCHAR(150) NOT NULL,
  city VARCHAR(120) NOT NULL,
  artist VARCHAR(150) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
